services:
  - type: web
    name: cotisations
    runtime: docker
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "true"
      - key: APP_URL
        value: https://cotisations.onrender.com
      - key: APP_KEY
        sync: false
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: ep-crimson-grass-aggr998r-pooler.c-2.eu-central-1.aws.neon.tech
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: neondb
      - key: DB_USERNAME
        value: neondb_owner
      - key: DB_PASSWORD
        sync: false # Set this in Render dashboard for security
      - key: LOG_CHANNEL
        value: stderr
      - key: SESSION_DRIVER
        value: cookie
      - key: CACHE_STORE
        value: file
